version: '3.8'

services:
  app:
    build: .
    container_name: game-list-app
    environment:
      - CONTEXT_PATH=/gameList
      - DB_URL=jdbc:h2:file:/data/game-list;AUTO_SERVER=TRUE;
      - DB_USER=sa
      - DB_PASS=password
    ports:
      - "8080:8080"
    volumes:
      - h2-data:/data
    restart: always

volumes:
  h2-data: